apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          image: 976193251196.dkr.ecr.eu-west-2.amazonaws.com/web/java-images:11767986597-1
          ports:
            - containerPort: 8080
